#!/bin/csh -f
#
# Run cmake with reasonable defaults. Why make the user do all these steps?
#
#
module purge
module load mepo
module load intel/2020Update4
module load cmake/3.24.2
module load anaconda
conda activate torch

mkdir -p build
cd build
cmake .. -DCMAKE_Fortran_COMPILER=ifort \
         -DCMAKE_INSTALL_PREFIX=../install
