---

# Experiment name
exp_name: CF2_c90_replay

# Determine the frequency (in hours) we want to read files.
# DO NOT CHANGE
freq_nhours: 3

# Starting and ending dates
# The format should be YYYYMMDD_HHz.
# If HH is not provided, it is assumed to be 00.
beg_date: 20230701_00z
end_date: 20230711_21z

# List each collection you want to read
# data_dir = Full path to the location of the GEOS CF files
# file_prefix = Prefix of individual file names
# fields = Field names you want to read in the files
# fields_map = New field names that will be used by AQcGAN.
#              There should be a one-to-one correspondance
#              with the previous list.
# level_id = Level index of interest.
#            If dealing with surface fields, set it to -1.
collection:
  gcc_2dx_ll:
    data_dir: /discover/nobackup/projects/gmao/aist-cf/pawales/experiments/CF2_c90_replay/holding/gcc_2dx_ll
    file_prefix: CF2_c90_replay.gcc_2dx_ll
    fields: ['CLDTT', 'EMIS_CO', 'EMIS_NO', 'EMIS_NO2', 'Met_SUNCOSmid', 'PHIS', 'TPREC', 'PS', 'SLP', 'T2M', 'TQV', 'U10M', 'V10M', 'ZPBL']
    fields_map: ['CLDTT', 'EMIS_CO', 'EMIS_NO', 'EMIS_NO2', 'Met_SUNCOSmid', 'PHIS', 'PRECTOT', 'PS', 'SLP', 'T2M', 'TQV', 'U10M', 'V10M', 'ZPBL']
    level_id: -1


  gcc_3dx_l:
    data_dir: /discover/nobackup/projects/gmao/geos_cf_dev/pawales/aist-cf/experiments/CF2_c90_replay/holding/gcc_3dx_ll
    file_prefix: CF2_c90_replay.gcc_3dx_ll
    fields: ['O3', 'CO', 'NO', 'NO2', 'Met_OPTD']
    fields_map: ['SpeciesConc_O3', 'SpeciesConc_CO', 'SpeciesConc_NO', 'SpeciesConc_NO2', 'Met_OPTD']
    level_id: 72

      #  met_tavg_1hr_glo_L1440x721_slv:
      #    data_dir: /discover/nobackup/projects/gmao/geos-cf-v2/CF2_control/holding/met_tavg_1hr_glo_L1440x721_slv
      #file_prefix: CF2.met_tavg_1hr_glo_L1440x721_slv
      #fields: [CLDTT, PHIS, TPREC, PS, SLP, ZPBL]
      #fields_map: [CLDTT, PHIS, PRECTOT, PS, SLP, ZPBL]
      #level_id: -1
      #
      #ems_tavg_1hr_glo_L1440x721_slv:
      #data_dir: /discover/nobackup/projects/gmao/geos-cf-v2/CF2_control/holding/ems_tavg_1hr_glo_L1440x721_slv
      #file_prefix: CF2.ems_tavg_1hr_glo_L1440x721_slv
      #fields: [EMIS_CO, EMIS_NO, EMIS_NO2]
      #fields_map: [EMIS_CO, EMIS_NO, EMIS_NO2]
      #level_id: -1
      #
      #chm_inst_1hr_glo_L1440x721_v72:
      #data_dir: /discover/nobackup/projects/gmao/geos-cf-v2/CF2_control/holding/chm_inst_1hr_glo_L1440x721_v72
      #file_prefix: CF2_control.chm_inst_1hr_glo_L1440x721_v72
      #fields: ['O3', 'CO', 'NO', 'NO2']
      #fields_map: [SpeciesConc_O3, SpeciesConc_CO, SpeciesConc_NO, SpeciesConc_NO2]
      #level_id: 72
