---

# Experiment name
exp_name: CF2_control

# Starting and ending dates
beg_date: 20230101
end_date: 20230102

# List each collection you want to read
# data_dir = Full path to the location of the GEOS CF files
# file_prefix = Prefix of individual file names
# fields = Field names you want to read in the files
# fields_map = New field names that will be used by AQcGAN. 
#              There should be a one-to-one correspondance 
#              with the previous list.
# level_id = Level index of interest.
#            If dealing with surface fields, set it to -1.
collection:
  met_tavg_1hr_glo_L1440x721_slv:
    data_dir: /discover/nobackup/projects/gmao/geos-cf-v2/CF2_control/holding/met_tavg_1hr_glo_L1440x721_slv
    file_prefix: CF2.met_tavg_1hr_glo_L1440x721_slv
    fields: [CLDTT, PHIS, TPREC, PS, SLP, ZPBL]
    fields_map: [CLDTT, PHIS, PRECTOT, PS, SLP, ZPBL]
    level_id: -1

  ems_tavg_1hr_glo_L1440x721_slv:
    data_dir: /discover/nobackup/projects/gmao/geos-cf-v2/CF2_control/holding/ems_tavg_1hr_glo_L1440x721_slv
    file_prefix: CF2.ems_tavg_1hr_glo_L1440x721_slv
    fields: [EMIS_CO, EMIS_NO, EMIS_NO2]
    fields_map: [EMIS_CO, EMIS_NO, EMIS_NO2]
    level_id: -1

  chm_inst_1hr_glo_L1440x721_v72:
    data_dir: /discover/nobackup/projects/gmao/geos-cf-v2/CF2_control/holding/chm_inst_1hr_glo_L1440x721_v72
    file_prefix: CF2_control.chm_inst_1hr_glo_L1440x721_v72
    fields: ['O3', 'CO', 'NO', 'NO2']
    fields_map: [SpeciesConc_O3, SpeciesConc_CO, SpeciesConc_NO, SpeciesConc_NO2]
    level_id: 72
