---

exp_name: CF2_control
beg_date: 20230101
end_date: 20230102
root_dir: /discover/nobackup/projects/gmao/geos-cf-v2
collection:
  met_tavg_1hr_glo_L1440x721_slv:
    file_prefix: CF2.met_tavg_1hr_glo_L1440x721_slv
    fields: [CLDTT, PHIS, TPREC, PS, SLP, ZPBL]
    fields_map: [CLDTT, PHIS, PRECTOT, PS, SLP, ZPBL]
    level_id: -1

  ems_tavg_1hr_glo_L1440x721_slv:
    file_prefix: CF2.ems_tavg_1hr_glo_L1440x721_slv
    fields: [EMIS_CO, EMIS_NO, EMIS_NO2]
    fields_map: [EMIS_CO, EMIS_NO, EMIS_NO2]
    level_id: -1

  chm_inst_1hr_glo_L1440x721_v72:
    file_prefix: CF2_control.chm_inst_1hr_glo_L1440x721_v72
    fields: ['O3', 'CO', 'NO', 'NO2']
    fields_map: [SpeciesConc_O3, SpeciesConc_CO, SpeciesConc_NO, SpeciesConc_NO2]
    level_id: 72
